# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('consola', models.CharField(max_length=200)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=7)),
                ('PEGI', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('companyia', models.CharField(max_length=200)),
                ('imatge', models.ImageField(max_length=200, upload_to='articles')),
                ('coleccionista', models.BooleanField(default=False)),
                ('detalls', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
