# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_usuari_venedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='usuari_venedor',
            new_name='usuari_comprador',
        ),
    ]
