# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
        ('articles', '0003_auto_20170508_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id_carro', models.AutoField(primary_key=True, serialize=False)),
                ('preu_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuaris.Usuari')),
            ],
        ),
        migrations.CreateModel(
            name='comanda',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantitat', models.IntegerField()),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='usuari_comprador',
        ),
        migrations.AddField(
            model_name='comanda',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_agafat', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.carro'),
        ),
    ]
