# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20170515_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
