# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carret',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_linia', models.AutoField(primary_key=True, serialize=False)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantitat', models.IntegerField()),
                ('id_comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandes.Carret')),
                ('id_producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
