# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_paypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='compte',
            field=models.IntegerField(default=12345678911234567890L, max_length=24),
            preserve_default=False,
        ),
    ]
