# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0003_usuari_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='compte',
            field=models.CharField(max_length=200),
        ),
    ]
