# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20170515_1347'),
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carret',
            name='data',
        ),
        migrations.RemoveField(
            model_name='carret',
            name='id_comanda',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='id_comanda',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='id_linia',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='id_producte',
        ),
        migrations.AddField(
            model_name='carret',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carret',
            name='preu_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='comanda',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_agafat', to='articles.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comandes.Carret'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='data',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 5, 15, 13, 47, 36, 902039, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
